name: nbois_user_client
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  collection: ^1.17.2
  envied: ^0.5.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^6.1.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  latlong2: ^0.9.0
  supabase_flutter: ^1.10.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  envied_generator: ^0.5.2

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
